//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TD1console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Avi
    {
        public int film { get; set; }
        public int utilisateur { get; set; }
        public string avis { get; set; }
        public double note { get; set; }
    
        public virtual Film FilmAvis { get; set; }
        public virtual Utilisateur UtilisateurAvis { get; set; }
    }
}
